version: '3.7'

services:

    zap:
        container_name: zap_docked
        image: owasp/zap2docker-stable
        ports:
            - 8080:8080
            - 8090:8090
        command: "zap-webswing.sh"

